import type { Report, Diagnosis, PolicyResult } from "../evaluation/types.js";
import { formatFailureType, formatSubtype } from "./helpers.js";

/**
 * Build structured markdown fix instructions for a conversation diagnosis.
 * Modeled after Converra's "Fix in Code" pattern — actionable runbook format.
 */
export function buildConversationFixMd(
  conv: Report["conversations"][0],
  report: Report,
): string {
  const d = conv.diagnosis;
  if (!d) return "";

  const lines: string[] = [];
  const headline = d.summary.split(".")[0] ?? d.summary;

  lines.push(`# Fix: ${headline}`);
  lines.push("");
  lines.push("## Problem");
  lines.push(`- **Severity:** ${d.severity}`);
  lines.push(`- **Root cause:** Step ${d.rootCauseTurn}${d.rootCauseAgent ? ` (${d.rootCauseAgent})` : ""}`);
  lines.push(`- **Type:** ${formatFailureType(d.failureType)} → ${formatSubtype(d.failureSubtype)}`);
  lines.push(`- **Confidence:** ${d.confidence}`);
  lines.push(`- **Conversation:** ${conv.id}`);

  lines.push("");
  lines.push("## What Happened");
  lines.push(d.summary);

  lines.push("");
  lines.push("## Impact");
  lines.push(d.impact);

  if (d.cascadeChain.length > 0) {
    lines.push("");
    lines.push("## Cascade");
    for (const step of d.cascadeChain) {
      lines.push(`- ${step}`);
    }
  }

  lines.push("");
  lines.push("## Recommended Fix");
  lines.push(d.fix);

  // Evidence from failing policy results
  const failingPolicies = conv.policyResults.filter((pr) => !pr.passed && pr.evidence);
  if (failingPolicies.length > 0) {
    lines.push("");
    lines.push("## Evidence");
    for (const pr of failingPolicies) {
      const policy = report.policies.find((p) => p.id === pr.policyId);
      lines.push(`### ${policy?.name ?? pr.policyId}`);
      lines.push(`> ${pr.evidence}`);
      lines.push("");
    }
  }

  if (d.blastRadius.length > 0) {
    lines.push("");
    lines.push("## Blast Radius");
    lines.push("Changing this may affect:");
    for (const r of d.blastRadius) {
      lines.push(`- ${r}`);
    }
  }

  lines.push("");
  lines.push("## How to Apply");
  lines.push(...getGuidanceForType(d));

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [agent-triage](https://github.com/converra/agent-triage)*");

  return lines.join("\n");
}

/**
 * Build structured markdown for a recommendation.
 */
export function buildRecommendationFixMd(
  rec: Report["failurePatterns"]["topRecommendations"][0],
  index: number,
): string {
  const lines: string[] = [];

  lines.push(`# Recommendation ${index + 1}: ${rec.title}`);
  lines.push("");
  lines.push("## Summary");
  lines.push(rec.description);
  lines.push("");
  lines.push("## Details");
  lines.push(`- **Failure types:** ${rec.targetFailureTypes.map(formatFailureType).join(", ")}`);
  lines.push(`- **Subtypes:** ${rec.targetSubtypes.map(formatSubtype).join(", ")}`);
  lines.push(`- **Affected conversations:** ${rec.affectedConversations}`);
  lines.push(`- **Confidence:** ${rec.confidence}`);

  lines.push("");
  lines.push("## How to Apply");
  const type = rec.targetFailureTypes[0] ?? "prompt_issue";
  lines.push(...getGuidanceForCategory(type));

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [agent-triage](https://github.com/converra/agent-triage)*");

  return lines.join("\n");
}

/**
 * Build structured markdown for a failure pattern (root cause category).
 */
export function buildPatternFixMd(
  pattern: Report["failurePatterns"]["byType"][0],
  affected: Report["conversations"],
): string {
  const lines: string[] = [];
  const label = formatFailureType(pattern.type);

  lines.push(`# Root Cause: ${label}`);
  lines.push("");
  lines.push(`- **Occurrences:** ${pattern.count}`);
  if (pattern.criticalCount > 0) lines.push(`- **Critical:** ${pattern.criticalCount}`);
  lines.push("");

  if (pattern.subtypes.length > 0) {
    lines.push("## Subtypes");
    for (const s of pattern.subtypes) {
      lines.push(`- ${formatSubtype(s.name)}: ${s.count} (${s.percentage}%)`);
    }
    lines.push("");
  }

  if (affected.length > 0) {
    lines.push("## Affected Conversations");
    for (const c of affected) {
      const summary = c.diagnosis?.summary ?? "Quality issue detected";
      const sev = c.diagnosis?.severity ?? "major";
      lines.push(`- **${c.id.slice(0, 10)}** (${sev}): ${summary}`);
    }
    lines.push("");
  }

  lines.push("## How to Fix");
  lines.push(...getGuidanceForCategory(pattern.type));

  lines.push("");
  lines.push("---");
  lines.push("*Generated by [agent-triage](https://github.com/converra/agent-triage)*");

  return lines.join("\n");
}

function getGuidanceForType(d: Diagnosis): string[] {
  return getGuidanceForCategory(d.failureType, d.failureSubtype);
}

function getGuidanceForCategory(type: string, subtype?: string): string[] {
  switch (type) {
    case "prompt_issue":
      return [
        "1. Open your agent's system prompt",
        "2. Locate the section that handles the failing scenario",
        subtype === "hallucination"
          ? "3. Add explicit guardrails: \"Do not make claims about [topic] unless stated in the knowledge base\""
          : subtype === "missing_escalation"
            ? "3. Add an escalation rule: \"When the user [trigger condition], hand off to [target]\""
            : subtype === "tone_violation"
              ? "3. Add tone instructions: \"When responding to [scenario], use [desired tone]\""
              : "3. Add or clarify the instruction that governs this behavior",
        "4. Test with the failing conversation to verify the fix",
      ];
    case "orchestration_issue":
      return [
        "1. Review your agent routing / orchestration config",
        subtype === "wrong_routing"
          ? "2. Check the routing conditions — the wrong handler is being selected"
          : subtype === "missing_handoff"
            ? "2. Add a handoff rule for this scenario — the agent is stuck instead of escalating"
            : "2. Check the step sequencing and handoff conditions",
        "3. Verify the routing logic handles edge cases in the failing conversation",
        "4. Test the full conversation flow end-to-end after the change",
      ];
    case "retrieval_rag_issue":
      return [
        "1. Check your knowledge base / RAG pipeline",
        subtype === "missing_tool_call"
          ? "2. The agent should have called a tool but didn't — check tool definitions and trigger conditions"
          : subtype === "wrong_retrieval"
            ? "2. The agent retrieved irrelevant context — check embedding quality and chunk size"
            : "2. Verify the retrieval pipeline returns relevant results for this query",
        "3. Test the retrieval with the exact user query from the failing step",
      ];
    case "model_limitation":
      return [
        "1. This may be a model capability issue, not a prompt issue",
        "2. Try a more capable model or simplify the task",
        "3. If the task requires long context, check if the model supports it",
        "4. Consider breaking the task into smaller, sequential steps",
      ];
    default:
      return [
        "1. Review the failing conversation and root cause analysis above",
        "2. Identify which part of your system prompt or config governs this behavior",
        "3. Make the targeted change described in the recommended fix",
        "4. Re-run agent-triage to verify the fix",
      ];
  }
}
